CREATE TABLE IF NOT EXISTS submissions (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    gpa NUMERIC(3,2) NOT NULL CHECK (gpa BETWEEN 0 AND 4),
    completed_courses VARCHAR(2000) NOT NULL CHECK (TRIM(completed_courses) <> ''),
    major VARCHAR(120) NOT NULL CHECK (TRIM(major) <> ''),
    career_goal VARCHAR(200) NOT NULL CHECK (TRIM(career_goal) <> ''),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
